uploads = []
outputs = []

[[generated]]
id = "iCkzwpUZhME0FVo92q4dn"
uri = "file://artifacts/mafioso/public/case-images/logo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "F2qx7QbtH6hme6x6slrHd"
uri = "file://artifacts/mafioso/public/case-images/case_01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XeiQeysRB5E-e_l4rrzDO"
uri = "file://artifacts/mafioso/public/case-images/case_02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "w7VAZn5UIxh2jOv_DV--l"
uri = "file://artifacts/mafioso/public/case-images/case_03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uZTjxEqaBZHEBhdH-b0nj"
uri = "file://artifacts/mafioso/public/case-images/case_04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SjpJLI-S36yqqtTe3tJKe"
uri = "file://artifacts/mafioso/public/case-images/case_05.png"
type = "image"
title = "generated_image"

[[generated]]
id = "AC-di2C-Zs7nA08doeGlp"
uri = "file://artifacts/mafioso/public/case-images/case_06.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ItO73p83BPcf1Kz7OiP9J"
uri = "file://artifacts/mafioso/public/case-images/case_07.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bCUMWVWt5BjFUML0k5vJI"
uri = "file://artifacts/mafioso/public/case-images/case_08.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fepoeinIyQn7YYBR1RiyE"
uri = "file://artifacts/mafioso/public/case-images/case_09.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9eW5862sGvNTzmfBQbmbL"
uri = "file://artifacts/mafioso/public/case-images/case_10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ihFgghkuD58rmDLTAMG6p"
uri = "file://artifacts/mafioso/public/case-images/case_11.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-CjND7sp0WFA-KdJobMXk"
uri = "file://artifacts/mafioso/public/case-images/case_12.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fLPSFd7uRLs7iMDTVSLjW"
uri = "file://artifacts/mafioso/public/case-images/case_13.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Qa157nWRk1yToBN38oI8f"
uri = "file://artifacts/mafioso/public/case-images/case_14.png"
type = "image"
title = "generated_image"

[[generated]]
id = "06Xr3GEhOEGtINHHR4Xgb"
uri = "file://artifacts/mafioso/public/case-images/case_15.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4jLbU102Gip-ccd6NZyqB"
uri = "file://artifacts/mafioso/public/case-images/case_16.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_QE5Ttm2LQH8Pfqn7cOiT"
uri = "file://artifacts/mafioso/public/case-images/case_17.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iJbEuBWG2NzpVK4Ci1NjQ"
uri = "file://artifacts/mafioso/public/case-images/case_18.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-lluLfZl3WssKx9K6R6Zq"
uri = "file://artifacts/mafioso/public/case-images/case_19.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JYME_Eul5FARt0AcA-nZ3"
uri = "file://artifacts/mafioso/public/case-images/case_20.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kq7tg7-mo4lqCKybGme1v"
uri = "file://artifacts/mafioso/public/case-images/case_21.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TF_AHSGtioj99UG4WIkuE"
uri = "file://artifacts/mafioso/public/case-images/case_22.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RtUvu5rGH5WMPccjFHQuk"
uri = "file://artifacts/mafioso/public/case-images/case_23.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Kd110HerZrgHx5bj1gd_R"
uri = "file://artifacts/mafioso/public/case-images/case_24.png"
type = "image"
title = "generated_image"

[[generated]]
id = "V9jRKqZ-3ZLiTNKsEECDk"
uri = "file://artifacts/mafioso/public/case-images/case_25.png"
type = "image"
title = "generated_image"

[[generated]]
id = "R8p85PWmcHD3J0vyB-COH"
uri = "file://artifacts/mafioso/public/case-images/case_26.png"
type = "image"
title = "generated_image"

[[generated]]
id = "O-c4X0RXqkFYqX93tVC-k"
uri = "file://artifacts/mafioso/public/case-images/case_27.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LeoXlMvnVLtYE9VKwOZ1s"
uri = "file://artifacts/mafioso/public/case-images/case_28.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Gz8P-mgsOHAnVbxh4BUqM"
uri = "file://artifacts/mafioso/public/case-images/case_29.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Fo1vsSr-xy-yIlxwnCaBx"
uri = "file://artifacts/mafioso/public/case-images/case_30.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ddqDJFLUjoKJfsQnl6YEW"
uri = "file://artifacts/mafioso/public/case-images/case5p_01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5b-YRnFA59MsGwc4dSavd"
uri = "file://artifacts/mafioso/public/case-images/case5p_02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mrUHynJZxoGsbi0-J7xHB"
uri = "file://artifacts/mafioso/public/case-images/case5p_03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z2YdXZwY22BY_ahWtHjxJ"
uri = "file://artifacts/mafioso/public/case-images/case5p_04.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VpLThU6DxnFyfSoCs1TGW"
uri = "file://artifacts/mafioso/public/case-images/case5p_05.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MUspGb9YTScsEPLzciHQv"
uri = "file://artifacts/mafioso/public/case-images/case5p_06.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Y1bO5N11avjqobS7Tvuqq"
uri = "file://artifacts/mafioso/public/case-images/case5p_07.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zjRfVuOwG74IZ9ONPCIg9"
uri = "file://artifacts/mafioso/public/case-images/case5p_08.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4_Ldx8LYX_WcSnmQWsTNh"
uri = "file://artifacts/mafioso/public/case-images/case5p_09.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BklRcM3QqumbkhUDf_Rqs"
uri = "file://artifacts/mafioso/public/case-images/case5p_10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Dm8beBn8Ie9U6_Id-HTbu"
uri = "file://artifacts/mafioso/public/case-images/case5p_11.png"
type = "image"
title = "bridge fraud crime scene"

[[generated]]
id = "XP0qihLkLJgDJHMk5MNZP"
uri = "file://artifacts/mafioso/public/case-images/case5p_12.png"
type = "image"
title = "forbidden diplomatic file"

[[generated]]
id = "cNA4OYc82MPH_QgbSqGHO"
uri = "file://artifacts/mafioso/public/case-images/case5p_13.png"
type = "image"
title = "minister night murder hotel"

[[generated]]
id = "c_vzyE5pZVprtMdW7Xytb"
uri = "file://artifacts/mafioso/public/case-images/case5p_14.png"
type = "image"
title = "football blood tournament crime"

[[generated]]
id = "lzP4gGVVxZtLL-dpkuHw5"
uri = "file://artifacts/mafioso/public/case-images/case5p_15.png"
type = "image"
title = "last manuscript theft"

[[generated]]
id = "-5Xn_mPEBFOFTI-bTA-nb"
uri = "file://artifacts/mafioso/public/case-images/case5p_16.png"
type = "image"
title = "port operation crime"

[[generated]]
id = "Gs3jIjXzjoWYmhfwZPVjJ"
uri = "file://artifacts/mafioso/public/case-images/case5p_17.png"
type = "image"
title = "poisoned harvest crime"

[[generated]]
id = "Czp9UQ-28VpcIRF2dey_Q"
uri = "file://artifacts/mafioso/public/case-images/case5p_18.png"
type = "image"
title = "cancelled flight murder airport"

[[generated]]
id = "jRWRN-sGsLCPCCXX3tLKO"
uri = "file://artifacts/mafioso/public/case-images/case5p_19.png"
type = "image"
title = "silent heart hospital crime"

[[generated]]
id = "Jlt6z9n0trzWxTj5fJ_m1"
uri = "file://artifacts/mafioso/public/case-images/case5p_20.png"
type = "image"
title = "future theft tech crime"

[[generated]]
id = "B82ftZbExBXYj-GRy047k"
uri = "file://artifacts/mafioso/public/case-images/case5p_21.png"
type = "image"
title = "bloody summit conference murder"

[[generated]]
id = "j953dFYvbk9X_xcsZqjmD"
uri = "file://artifacts/mafioso/public/case-images/case5p_22.png"
type = "image"
title = "fashion lies fraud crime"

[[generated]]
id = "9WMlYp2OzDl9C7tqbAVys"
uri = "file://artifacts/mafioso/public/case-images/case5p_23.png"
type = "image"
title = "school truth murder lesson"

[[generated]]
id = "bna8kKVC7OCn2q2wg6Uak"
uri = "file://artifacts/mafioso/public/case-images/case5p_24.png"
type = "image"
title = "power station sabotage darkness"

[[generated]]
id = "JvNx1XjzDXMNNhj93BfGn"
uri = "file://artifacts/mafioso/public/case-images/case5p_25.png"
type = "image"
title = "charity deception embezzlement"

[[generated]]
id = "G7h5CIoy2zD0vxuUQM3NY"
uri = "file://artifacts/mafioso/public/case-images/case5p_26.png"
type = "image"
title = "diplomatic thread organized crime"

[[generated]]
id = "ZvhZuFeg5o2ED2g00SIOg"
uri = "file://artifacts/mafioso/public/case-images/case5p_27.png"
type = "image"
title = "last dance nightclub murder"

[[generated]]
id = "4wr11wAHmRlWdD0pAJtkc"
uri = "file://artifacts/mafioso/public/case-images/case5p_28.png"
type = "image"
title = "green lie energy fraud"

[[generated]]
id = "xb_0DFWbpMA9VHC9yeWJm"
uri = "file://artifacts/mafioso/public/case-images/case5p_29.png"
type = "image"
title = "hidden heirs inheritance murder"

[[generated]]
id = "12ojrqvA2vB_bhYY8a1_X"
uri = "file://artifacts/mafioso/public/case-images/case5p_30.png"
type = "image"
title = "space center countdown sabotage"
